/**
 * API hata kodları. İstemci bu kodlara göre dallanır; `message` alanı
 * kullanıcıya gösterilmek içindir ve değişebilir.
 *
 * Karşılıkları: docs/01-is-analizi.md §3
 */
export enum ErrorCode {
  // Kimlik & yetki
  AUTH_EMAIL_TAKEN = 'AUTH_EMAIL_TAKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Genel
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Katalog
  BOOK_ISBN_TAKEN = 'BOOK_ISBN_TAKEN',
  BOOK_HAS_ACTIVE_BORROWINGS = 'BOOK_HAS_ACTIVE_BORROWINGS',
  BOOK_OUT_OF_STOCK = 'BOOK_OUT_OF_STOCK',

  // Ödünç
  BORROW_LIMIT_EXCEEDED = 'BORROW_LIMIT_EXCEEDED',
  BORROW_ALREADY_ACTIVE = 'BORROW_ALREADY_ACTIVE',
  BORROW_ALREADY_RETURNED = 'BORROW_ALREADY_RETURNED',

  // Rezervasyon
  RESERVATION_DUPLICATE = 'RESERVATION_DUPLICATE',
  RESERVATION_BOOK_IN_HAND = 'RESERVATION_BOOK_IN_HAND',

  // Yorum
  REVIEW_DUPLICATE = 'REVIEW_DUPLICATE',
  REVIEW_RATING_RANGE = 'REVIEW_RATING_RANGE',
}
